// AUTO-GENERATED by web/scripts/sync-abi.mjs. Do not edit by hand.

export { stellarArenaAbi } from './stellarArena'
export { iStellarStoreAbi } from './iStellarStore'
export { iVladTokenAbi } from './iVladToken'
